[project]
name = "shipped-it-cli"
version = "0.1.0"
description = "CLI Entrypoint of shipped-it"
readme = "README.md"
authors = [
    { name = "Kazuya Takei", email = "myself@attakei.net" }
]
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
    "python-dotenv>=1.2.1",
    "shipped-it",
]

[project.scripts]
shipped = "shipped_it_cli:main"

[build-system]
requires = ["uv_build>=0.8.9,<0.9.0"]
build-backend = "uv_build"
